# install.packages('tidyverse')
# install.packages('shiny')
# install.packages('shinythemes')
# install.packages('rsconnect')
# install.packages("dygraphs")
# install.packages('shinyjs')
# install.packages('plotly')
# install.packages('png')
# install.packages('ggplot2')
# install.packages('ggplotify')
# install.packages("DescTools")
# install.packages('argonR')
# install.packages('argonR')
# install.packages('devtools')
# install.packages('geobr')
# install.packages('sf')
#install.packages('data.table')
#install.packages('scales')

library(tidyverse)
library(shiny)
library(shinythemes)
library(rsconnect)
library(dygraphs)
library(xts)
library(dplyr)
library(zoo)
library(plotly)
library(shinyjs)
library(ggplot2)
library(ggplotify)
library(DescTools)
library(readxl)
library(shinydashboard)
library(shinyWidgets)
library(rintrojs)
library(shinyjs)
library(lubridate)
library(plotly)
library(geobr)
library(sf)
library(data.table)
library(scales)

urlfile <- "https://raw.githubusercontent.com/wcota/covid19br/master/cases-brazil-states.csv"
mydata_Brazil <- read_csv(url(urlfile))
Dados_sociodemograficos <- read_excel("Dados_sociodemograficos_2.xlsx")

source('ui.R') 
source('server.R')

shinyApp(ui = ui,
         server = server)